In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
train_data=pd.read_csv('trainGT.csv')
test_data=pd.read_csv('testGT.csv')

In [3]:
train_data.head()

Unnamed: 0  pelvic_incidence  pelvic_tilt  lumbar_lordosis_angle  \
0          37         35.703458    19.443253              20.700000   
1          16         63.834982    20.362507              54.552434   
2          55         47.657730    13.277385              36.679985   
3         154         41.187770     5.792974              42.867392   
4         279         48.801909    18.017762              52.000000   

   sacral_slope  pelvic_radius  degree_spondylolisthesis  pelvic_slope  \
0     16.260205     137.540613                 -0.263490      0.882807   
1     43.472475     112.309491                 -0.622527      0.560675   
2     34.380345      98.249781                  6.273012      0.972556   
3     35.394796     103.348880                 27.660277      0.044130   
4     30.784147     139.150407                 10.442862      0.105014   

   direct_tilt  thoracic_slope  cervical_tilt  sacrum_angle  scoliosis_slope  \
0      32.5864         12.7274        9.53575    -14.695641          38.7458   
1      10.7690         16.8116       11.41344      2.676002          17.3859   
2      18.2046         16.9817       12.32724    -26.375211          14.1334   
3      21.0757         10.5374        9.66748     -9.571667          30.5253   
4      26.1245         19.2659        8.31303    -22.690688          39.6096   

   Label  
0      1  
1      1  
2      1  
3      1  
4      0

310 Observations, 13 Attributes (12 Numeric Predictors, 1 Binary Class Attribute - No Demographics)

Lower back pain can be caused by a variety of problems with any parts of the complex, interconnected network of spinal muscles, nerves, bones, discs or tendons in the lumbar spine. Typical sources of low back pain include:

The large nerve roots in the low back that go to the legs may be irritated
The smaller nerves that supply the low back may be irritated
The large paired lower back muscles (erector spinae) may be strained
The bones, ligaments or joints may be damaged
An intervertebral disc may be degenerating
An irritation or problem with any of these structures can cause lower back pain and/or pain that radiates or is referred to other parts of the body. Many lower back problems also cause back muscle spasms, which don't sound like much but can cause severe pain and disability.

While lower back pain is extremely common, the symptoms and severity of lower back pain vary greatly. A simple lower back muscle strain might be excruciating enough to necessitate an emergency room visit, while a degenerating disc might cause only mild, intermittent discomfort.

This data set is about to identify a person is abnormal or normal using collected physical spine details/data.

In [4]:
train_data.describe()

Unnamed: 0  pelvic_incidence  pelvic_tilt  lumbar_lordosis_angle  \
count  207.000000        207.000000   207.000000             207.000000   
mean   157.811594         59.499959    16.958779              50.893909   
std     89.463820         17.386182     9.607004              17.665639   
min      0.000000         26.147921    -6.554948              14.000000   
25%     84.000000         45.969094    10.145246              37.000000   
50%    159.000000         56.535051    15.969344              48.000000   
75%    234.000000         72.391518    21.122577              61.821226   
max    309.000000        129.834041    48.903653             100.744220   

       sacral_slope  pelvic_radius  degree_spondylolisthesis  pelvic_slope  \
count    207.000000     207.000000                207.000000    207.000000   
mean      42.541181     118.574496                 25.949329      0.472566   
std       13.651320      12.609351                 40.354828      0.283586   
min       13.516568      81.024541                -11.058179      0.005045   
25%       33.277979     111.533428                  1.534517      0.232902   
50%       41.987212     118.588669                  9.064582      0.473130   
75%       51.883721     125.536899                 40.446654      0.699979   
max      121.429566     163.071041                418.543082      0.998827   

       direct_tilt  thoracic_slope  cervical_tilt  sacrum_angle  \
count   207.000000      207.000000     207.000000    207.000000   
mean     21.044952       13.007243      11.931664    -13.761669   
std       8.585896        3.413408       2.979811     12.490424   
min       7.055100        7.037800       7.030600    -35.287375   
25%      12.949750       10.285900       9.524230    -24.849199   
50%      21.501300       12.843200      11.953700    -12.363109   
75%      28.181650       15.703600      14.378560     -2.949825   
max      36.628500       19.324000      16.821080      6.972071   

       scoliosis_slope       Label  
count       207.000000  207.000000  
mean         26.027024    0.657005  
std          10.624010    0.475861  
min           7.069800    0.000000  
25%          16.988800    0.000000  
50%          26.891700    1.000000  
75%          34.886250    1.000000  
max          44.341200    1.000000

In [5]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 14 columns):
Unnamed: 0                  207 non-null int64
pelvic_incidence            207 non-null float64
pelvic_tilt                 207 non-null float64
lumbar_lordosis_angle       207 non-null float64
sacral_slope                207 non-null float64
pelvic_radius               207 non-null float64
degree_spondylolisthesis    207 non-null float64
pelvic_slope                207 non-null float64
direct_tilt                 207 non-null float64
thoracic_slope              207 non-null float64
cervical_tilt               207 non-null float64
sacrum_angle                207 non-null float64
scoliosis_slope             207 non-null float64
Label                       207 non-null int64
dtypes: float64(12), int64(2)
memory usage: 22.8 KB


In [6]:
from sklearn.ensemble import RandomForestClassifier
def rf_ml(Xtrain,Ytrain,Xtest):
    model = RandomForestClassifier()
    model.fit(Xtrain,Ytrain)
    labels = model.predict(Xtest)
    return labels

In [7]:
from sklearn.svm import SVC
def svc_ml(Xtrain,Ytrain,Xtest):
    model = SVC()
    model.fit(Xtrain,Ytrain)
    labels = model.predict(Xtest)
    return labels


In [8]:
from sklearn.tree import DecisionTreeClassifier
def dt_ml(Xtrain,Ytrain,Xtest):
    model = DecisionTreeClassifier()
    model.fit(Xtrain,Ytrain)
    labels = model.predict(Xtest)
    return labels

# Reasons I didnt inlcude other classification models:
KNN is not good with higher number of dimensions.
NB is not suitable for this problem according to me as there is no 3rd data table available to draw conclusions about the probability of abnormility, maybe one can split the data columns in such a way that NB can be used, but its still not very reliable for this, maybe for some other day for NLP related problems.


In [9]:
train_data.columns

Index(['Unnamed: 0', 'pelvic_incidence', 'pelvic_tilt',
       'lumbar_lordosis_angle', 'sacral_slope', 'pelvic_radius',
       'degree_spondylolisthesis', 'pelvic_slope', 'direct_tilt',
       'thoracic_slope', 'cervical_tilt', 'sacrum_angle', 'scoliosis_slope',
       'Label'],
      dtype='object')

In [10]:
Xtrain = train_data[['pelvic_incidence', 'pelvic_tilt',
       'lumbar_lordosis_angle', 'sacral_slope', 'pelvic_radius',
       'degree_spondylolisthesis', 'pelvic_slope', 'direct_tilt',
       'thoracic_slope', 'cervical_tilt', 'sacrum_angle', 'scoliosis_slope']]

In [11]:
Ytrain=train_data['Label']

In [12]:
Xtest=  test_data[['pelvic_incidence', 'pelvic_tilt',
       'lumbar_lordosis_angle', 'sacral_slope', 'pelvic_radius',
       'degree_spondylolisthesis', 'pelvic_slope', 'direct_tilt',
       'thoracic_slope', 'cervical_tilt', 'sacrum_angle', 'scoliosis_slope']]

In [13]:
Pred_dt=dt_ml(Xtrain,Ytrain,Xtest)
Pred_rf=rf_ml(Xtrain,Ytrain,Xtest)
Pred_svc=svc_ml(Xtrain,Ytrain,Xtest)


C:\Users\aakas\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\aakas\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [14]:
Ytest=test_data['Label']

In [15]:
from sklearn.metrics import classification_report
print(classification_report(Ytest,Pred_dt))
print(classification_report(Ytest,Pred_rf))
print(classification_report(Ytest,Pred_svc))

              precision    recall  f1-score   support

           0       0.59      0.59      0.59        29
           1       0.84      0.84      0.84        74

    accuracy                           0.77       103
   macro avg       0.71      0.71      0.71       103
weighted avg       0.77      0.77      0.77       103

              precision    recall  f1-score   support

           0       0.60      0.62      0.61        29
           1       0.85      0.84      0.84        74

    accuracy                           0.78       103
   macro avg       0.72      0.73      0.73       103
weighted avg       0.78      0.78      0.78       103

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        29
           1       0.72      1.00      0.84        74

    accuracy                           0.72       103
   macro avg       0.36      0.50      0.42       103
weighted avg       0.52      0.72      0.60       103



C:\Users\aakas\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Confusion matrix to understand this better.

In [16]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Ytest,Pred_dt)

array([[17, 12],
       [12, 62]], dtype=int64)

In [17]:
confusion_matrix(Ytest,Pred_rf)

array([[18, 11],
       [12, 62]], dtype=int64)

In [18]:
confusion_matrix(Ytest,Pred_svc)

array([[ 0, 29],
       [ 0, 74]], dtype=int64)

Using GridSearchCV now.

In [19]:
from sklearn.model_selection import GridSearchCV
def grid_dt(Xtrain,Ytrain,Xtest):
    model=DecisionTreeClassifier()
    parameters = {'max_depth':np.arange(1,31), 'min_samples_leaf':[1,2,3,4, 5, 10, 20, 50, 100],'min_samples_split':[2,3],'criterion':['gini','entropy']}
    gs_dt=GridSearchCV(estimator=model,param_grid=parameters)
    gs_dt.fit(Xtrain,Ytrain)
    print(gs_dt.best_estimator_)
    new_model=gs_dt.best_estimator_
    new_model.fit(Xtrain,Ytrain)
    labels = new_model.predict(Xtest)
    return labels
    

In [20]:
GridPredDT = grid_dt(Xtrain,Ytrain,Xtest)
print(classification_report(Ytest,GridPredDT))
confusion_matrix(Ytest,GridPredDT)

C:\Users\aakas\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=3,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       0.61      0.66      0.63        29
           1       0.86      0.84      0.85        74

    accuracy                           0.79       103
   macro avg       0.74      0.75      0.74       103
weighted avg       0.79      0.79      0.79       103



C:\Users\aakas\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


array([[19, 10],
       [12, 62]], dtype=int64)

In [21]:
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
def grid_rf(Xtrain,Ytrain,Xtest):

    model=RandomForestClassifier()
    pca = PCA()
    pipe = Pipeline(steps=[('pca', pca), ('model', model)])
    param_grid = { 'pca__svd_solver':['full'],'pca__n_components':[2,4,6,8,10],'model__n_estimators': np.arange(100,700,200), 'model__max_features': ['auto', 'sqrt', 'log2'],'model__max_depth':np.arange(1,6),'model__criterion':['gini']}
    gs_rf=GridSearchCV(estimator=pipe,param_grid=param_grid)
    gs_rf.fit(Xtrain,Ytrain)
    print(gs_rf.best_estimator_)
    new_model=gs_rf.best_estimator_
    new_model.fit(Xtrain,Ytrain)
    labels = new_model.predict(Xtest)
    return labels
    

In [22]:
model=RandomForestClassifier()
pca = PCA()
pipe = Pipeline(steps=[('pca', pca), ('model', model)])
pipe.get_params().keys()

dict_keys(['memory', 'steps', 'verbose', 'pca', 'model', 'pca__copy', 'pca__iterated_power', 'pca__n_components', 'pca__random_state', 'pca__svd_solver', 'pca__tol', 'pca__whiten', 'model__bootstrap', 'model__class_weight', 'model__criterion', 'model__max_depth', 'model__max_features', 'model__max_leaf_nodes', 'model__min_impurity_decrease', 'model__min_impurity_split', 'model__min_samples_leaf', 'model__min_samples_split', 'model__min_weight_fraction_leaf', 'model__n_estimators', 'model__n_jobs', 'model__oob_score', 'model__random_state', 'model__verbose', 'model__warm_start'])

In [23]:
GridPredRF = grid_rf(Xtrain,Ytrain,Xtest)
print(classification_report(Ytest,GridPredRF))
confusion_matrix(Ytest,GridPredRF)

C:\Users\aakas\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\aakas\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Pipeline(memory=None,
         steps=[('pca',
                 PCA(copy=True, iterated_power='auto', n_components=8,
                     random_state=None, svd_solver='full', tol=0.0,
                     whiten=False)),
                ('model',
                 RandomForestClassifier(bootstrap=True, class_weight=None,
                                        criterion='gini', max_depth=5,
                                        max_features='auto',
                                        max_leaf_nodes=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=300, n_jobs=None,
                                        oob_score=False, random_state=None,
                                        verbose=0, war

array([[16, 13],
       [11, 63]], dtype=int64)

In [25]:
from sklearn.metrics import f1_score
print('F1 Score for Decision tree  ----- {}'.format(f1_score(Ytest,Pred_dt)))
print('F1 Score for Random Forest  ----- {}'.format(f1_score(Ytest,Pred_rf)))
print('F1 Score for Decision tree with GridSearch  ----- {}'.format(f1_score(Ytest,GridPredDT)))
print('F1 Score for Random forest with GridSearch ----- {}'.format(f1_score(Ytest,GridPredRF)))

F1 Score for Decision tree  ----- 0.8378378378378378
F1 Score for Random Forest  ----- 0.8435374149659863
F1 Score for Decision tree with GridSearch  ----- 0.8493150684931507
F1 Score for Random forest with GridSearch ----- 0.8400000000000001


In [24]:
sub = pd.read_csv('sample_submission.csv')

In [27]:
sub['Label']=GridPredRF

In [29]:
sub.to_csv('Submission2.csv',index=False)